# Generated by Django 5.0 on 2023-12-19 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_coment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coment',
            new_name='Comment',
        ),
    ]
